openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /api/update-config:
    post:
      summary: Simulates a config change in production
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
      responses:
        '200':
          description: Simulated config update

